In [1]:
import numpy as np

In [3]:
np.random.seed(0)
A = np.random.randint(0,20,[2,3])
A

array([[12, 15,  0],
       [ 3,  3,  7]])

In [4]:
A.sum(axis=0)

array([15, 18,  7])

In [5]:
A.sum(axis=1)

array([27, 13])

In [6]:
A.mean(axis=0)

array([7.5, 9. , 3.5])

In [8]:
A.argmin(axis=0) #la position de la valeur minimale

array([1, 1, 0], dtype=int64)

In [10]:
A.sort()
A

array([[ 0, 12, 15],
       [ 3,  3,  7]])

In [11]:
A.argsort()

array([[0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [12]:
A.std()

5.312459150169743

In [13]:
A.std(axis=0)

array([1.5, 4.5, 4. ])

In [21]:
np.corrcoef(A, dtype=np.float16)


array([[1.   , 0.655],
       [0.655, 1.   ]], dtype=float16)

In [22]:
np.corrcoef(A)[0,1]

0.6546536707079771

In [24]:
A

array([[ 0, 12, 15],
       [ 3,  3,  7]])

In [23]:
np.unique(A, return_counts=True)

(array([ 0,  3,  7, 12, 15]), array([1, 2, 1, 1, 1], dtype=int64))

In [36]:
#IMPORTANT de 35 - 43
B = np.random.randint(0,10,[5,5])
B

array([[4, 1, 4, 9, 8],
       [1, 1, 7, 9, 9],
       [3, 6, 7, 2, 0],
       [3, 5, 9, 4, 4],
       [6, 4, 4, 3, 4]])

In [41]:
values , counts =np.unique(B, return_counts=True)
np.unique(B, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1, 3, 1, 3, 7, 1, 2, 2, 1, 4], dtype=int64))

In [38]:
values

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
counts.argsort()

array([0, 2, 5, 8, 6, 7, 1, 3, 9, 4], dtype=int64)

In [40]:
values[counts.argsort()]

array([0, 2, 5, 8, 6, 7, 1, 3, 9, 4])

In [43]:
for i, j in zip(values[counts.argsort()], counts[counts.argsort()]):
    print('le nombre {} apparaît {} fois'.format(i,j))

le nombre 0 apparaît 1 fois
le nombre 2 apparaît 1 fois
le nombre 5 apparaît 1 fois
le nombre 8 apparaît 1 fois
le nombre 6 apparaît 2 fois
le nombre 7 apparaît 2 fois
le nombre 1 apparaît 3 fois
le nombre 3 apparaît 3 fois
le nombre 9 apparaît 4 fois
le nombre 4 apparaît 7 fois


In [67]:
#nan : valeur manquante (not a number)
np.random.seed(0)
Y = np.random.randn(3,4)
Y

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351]])

In [68]:
Y[0,3] = np.nan
Y[1,3] = np.nan
Y[2,3] = np.nan
Y


array([[ 1.76405235,  0.40015721,  0.97873798,         nan],
       [ 1.86755799, -0.97727788,  0.95008842,         nan],
       [-0.10321885,  0.4105985 ,  0.14404357,         nan]])

In [69]:
Y.mean()

nan

In [70]:
np.nanmean(Y)

0.603859920838385

In [71]:
np.isnan(Y).sum()

3

In [72]:
#pourcentage de valeurs manquantes dans notre matrice
np.isnan(Y).sum()/Y.size

0.25

In [73]:
#remplacer les valeurs manquantes par la moyenne
Y[np.isnan(Y)]= np.nanmean(Y)
Y

array([[ 1.76405235,  0.40015721,  0.97873798,  0.60385992],
       [ 1.86755799, -0.97727788,  0.95008842,  0.60385992],
       [-0.10321885,  0.4105985 ,  0.14404357,  0.60385992]])

In [74]:
np.isnan(Y).sum()

0

In [79]:
#Calculer déterminant
X = np.random.randint(0,10,[2,2])
X

array([[0, 3],
       [5, 0]])

In [80]:
np.linalg.det(X)

-15.0

In [82]:
#inverser det matrice
np.linalg.pinv(X)

array([[0.        , 0.2       ],
       [0.33333333, 0.        ]])

In [83]:
#Valeurs propres = eingen value / vecteurs propres = eigen vector >> (Principle Component Analysis)
np.linalg.eig(X)

(array([ 3.87298335, -3.87298335]),
 array([[ 0.61237244, -0.61237244],
        [ 0.79056942,  0.79056942]]))

In [84]:
#Standardisation d'un dataset !!!! (très utilisé en machine learning)
# Z-score normalization formula:    x' = (x-mean(x))/std(x)

np.random.seed(0)
F = np.random.randint(0,100,[10,5])
F


array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58],
       [65, 39, 87, 46, 88],
       [81, 37, 25, 77, 72],
       [ 9, 20, 80, 69, 79],
       [47, 64, 82, 99, 88],
       [49, 29, 19, 19, 14],
       [39, 32, 65,  9, 57],
       [32, 31, 74, 23, 35]])

In [90]:
def z_score(x):
    x1 = (x-np.mean(x, axis=0))/np.std(x, axis=0)
    return x1

In [91]:
z_score(F)

array([[-0.02206157,  0.        ,  0.13173823,  0.72539252,  0.10755798],
       [-1.56637126,  1.61579632, -1.48676006, -0.33034307,  0.96802178],
       [ 1.12513992,  1.84021247,  1.03508612, -1.14768676, -0.27965074],
       [ 0.90452425, -0.35906585,  0.99744662,  0.0102168 ,  1.01104497],
       [ 1.6104944 , -0.44883231, -1.33620208,  1.0659524 ,  0.32267393],
       [-1.56637126, -1.21184724,  0.73397016,  0.7935045 ,  0.62383626],
       [ 0.11030784,  0.76301493,  0.80924915,  1.81518411,  1.01104497],
       [ 0.1985541 , -0.80789816, -1.56203905, -0.90929485, -2.17267111],
       [-0.24267724, -0.67324847,  0.16937773, -1.24985473, -0.32267393],
       [-0.55153918, -0.7181317 ,  0.50813319, -0.77307091, -1.26918412]])

In [93]:
np.std(F, axis=0)

array([22.66384786, 22.28003591, 26.5678377 , 29.36341261, 23.2432786 ])

In [94]:
#standard deviation : distribution normale standard >> facilite énormément l'apprentissage stats pck les données sont très bien
#répartis
np.std(z_score(F), axis=0)

array([1., 1., 1., 1., 1.])