In [1]:
#Le Pre-Processing représnte parfois 80% du travail d'un Data Scientist
import numpy as np
   
    

In [2]:
#Encoder (transformer valeurs qualitatives en valeurs numériques)
        
        #Ordinal encoders:  LabelEncoder() , OrdinalEncoder()
   
vect = np.array(['chat', 'chien', 'chat', 'loup'])

In [4]:
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder

In [5]:
encoder = LabelEncoder()

In [6]:
encoder.fit(vect)

LabelEncoder()

In [7]:
encoder.transform(vect)

array([0, 1, 0, 2])

In [10]:
encoder.inverse_transform(np.array([0, 0, 0, 2,1,2]))

array(['chat', 'chat', 'chat', 'loup', 'chien', 'loup'], dtype='<U5')

In [11]:
        #OneHotEncoders : LabelBinarizer, MultiLabelBinarizer, OneHotEncoder
    
from sklearn.preprocessing import LabelBinarizer    

In [12]:
encoder1= LabelBinarizer()

In [15]:
encoder1.fit_transform(vect)

array([[1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1]])

In [16]:
encoder1.inverse_transform(np.array([[1, 0, 0],
                                     [0, 1, 0],
                                     [1, 0, 0],
                                     [0, 0, 1]]))

array(['chat', 'chien', 'chat', 'loup'], dtype='<U5')

### Exemple de Tranformer-Estimator-Test

In [26]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [55]:
iris = load_iris()

X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(X, y)

In [56]:
#Transformer
from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()
X_transformed = std_scaler.fit_transform(X_train)

In [57]:
#Estimator
from sklearn.linear_model import LogisticRegression

log = LogisticRegression(max_iter=10000)
log.fit(X_transformed,y_train)

LogisticRegression(max_iter=10000)

In [62]:
#Test
from sklearn.metrics import *

X_test_tr = std_scaler.fit_transform(X_test)

log.predict(X_test_tr)

array([1, 2, 1, 0, 2, 1, 2, 1, 1, 1, 0, 1, 2, 2, 2, 1, 0, 1, 1, 1, 1, 2,
       2, 0, 0, 1, 0, 1, 1, 2, 2, 0, 2, 0, 2, 1, 1, 1])

### Refaire le Transformer-Estimator-Test avec le Pipeline (plus facile)

In [63]:
from sklearn.pipeline import make_pipeline

In [64]:
model = make_pipeline(StandardScaler(), LogisticRegression())

model.fit(X_train, y_train)

model.predict(X_test)

array([1, 2, 2, 0, 2, 2, 2, 1, 1, 1, 0, 1, 2, 2, 2, 1, 0, 2, 1, 1, 1, 2,
       2, 0, 0, 1, 0, 1, 1, 2, 2, 0, 2, 0, 2, 1, 1, 1])

### GridSearchCV avec Pipeline

In [66]:
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import PolynomialFeatures

In [68]:
model = make_pipeline(PolynomialFeatures(), StandardScaler(), LogisticRegression())

params = {
    'polynomialfeatures__degree':[2,3,4],
    'logisticregression__C':[0.5,1,1.5]
}

grid = GridSearchCV(model, params, cv=5)


In [69]:
grid.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('polynomialfeatures',
                                        PolynomialFeatures()),
                                       ('standardscaler', StandardScaler()),
                                       ('logisticregression',
                                        LogisticRegression())]),
             param_grid={'logisticregression__C': [0.5, 1, 1.5],
                         'polynomialfeatures__degree': [2, 3, 4]})

In [70]:
grid.best_score_

0.9731225296442687

In [71]:
grid.best_params_

{'logisticregression__C': 0.5, 'polynomialfeatures__degree': 3}

In [81]:
from sklearn.preprocessing import PolynomialFeatures

Q = np.array([5, 7.5, 10])

Poly = PolynomialFeatures()

In [83]:
Poly.fit_transform(Q.reshape(1,-1))

array([[  1.  ,   5.  ,   7.5 ,  10.  ,  25.  ,  37.5 ,  50.  ,  56.25,
         75.  , 100.  ]])